### ISSUE TITLE
Why is gcloud installed on the host automatically, and why isn't it documented?

### ISSUE THREAD

**Issue by sbrl** [bitnami/minideb#107]
**Description**
When I  build minideb from the latest master, the script attempts to automatically install gcloud.

**Steps to reproduce the issue:**

1. `git clone https://github.com/bitnami/minideb.git`
2. `cd minideb`
3. `sudo make buster`

**Describe the results you received:**

The build script attempts to add a new apt repository to the _host_ system and install a `gcloud` package.

Checking the documentation reveals nothing about the purpose of the installation of this package at all.

**Describe the results you expected:**

The documentation (e.g. the README) would detail all dependencies required and why. The documentation should be clear that all the dependencies listed, if not installed already, will be installed automatically.

**Additional information you deem important (e.g. issue happens only occasionally):**

This isn't a "technical" issue per say, but more of an issue of principle that dependencies such as the Google Cloud SDK  should be documented in the README - *especially* if it is going to be installed on  the *host system* automatically.

This is because automatic installation of the google cloud sdk could potentially be seen to be some kind of malware / spyware if it isn't expected.

**Version** latest master

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:18:46 2021
 OS/Arch:           linux/arm
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:16:18 2021
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 39
  Running: 0
  Paused: 0
  Stopped: 39
 Images: 880
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.83-v7l+
 Operating System: Raspbian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: armv7l
 CPUs: 4
 Total Memory: 1.872GiB
 Name: wopplefox
 ID: IGKV:TW64:XT2V:S6IE:6XDN:XAP3:K3SV:6W7P:JZLD:TJMO:ODNT:WNUF
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  registry.service.mooncarrot.space:5000
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory TCP limit support
WARNING: No oom kill disable support

```

- Output of `docker-compose version` (if applicable):

```
-bash: docker-compose: command not found
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Docker on fully-patched Raspberry Pi OS (based on Debian Buster).

**Comment by migruiz4** [comment]
Hi @sbrl ,

Thank you for reporting this issue.

This PR removes the `gcloud` dependency from `installed-requirements` as it is a publishing dependency and is not necessary to build the image: https://github.com/bitnami/minideb/pull/108/files

**Comment by sbrl** [comment]
Ah, wasn't expecting that! Many thanks for the quick resolution :-)

**Comment by migruiz4** [comment]
I'm happy to help.

Anything else I could do to help you?

**Comment by sbrl** [comment]
Just tested it - it works just fine!

Sorry, I think I must have forgotten to close this issue earlier.

Thanks for the help!
