### ISSUE TITLE
can not run on arm server

### ISSUE THREAD

**Issue by lxm** [bitnami/minideb#109]
![image](https://user-images.githubusercontent.com/1918195/112414969-fa8dbd00-8d5d-11eb-9a2e-118833e2c861.png)

multi arch images displayed to support

but when run on arm server
got "exec format error"

**Comment by juamedgod** [comment]
Hi,

Did you get any warning when pulling the image (or when running it) related to the arch not matching the detected host platform? 

To make sure the right arch image is being used, could you pull bitnami/minideb:buster-arm64 instead? Could you send us the output of executing in your host:

```
uname -a
```

**Comment by lxm** [comment]
no  warnings when pulling the image

outputs of `uname -a ` on host
```
Linux xxxx-g4im6 4.19.36-vhulk1907.1.0.h702.eulerosv2r8.aarch64 #1 SMP Mon Mar 16 00:02:15 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
```
`bitnami/minideb:buster-arm64` works well
`bitnami/minideb:buster`  will got error

```
container start initialization failed: standard_init_linux.go:219: exec user process caused "exec format error"
```

**Comment by rafariossaa** [comment]
Hi
  The error you got for `bitnami/minideb:buster` is normal as that image is for amd64 architectures.

**Comment by rafariossaa** [comment]
Hi,
  I tried on a raspberry pi 4 with raspbian 64 bit and it worked for me:

  ```
pi@raspberrypi:~ $ docker pull bitnami/minideb
Using default tag: latest
latest: Pulling from bitnami/minideb
f265f31cbb78: Pull complete 
Digest: sha256:53c2e148121eaa25b5f264463d4d1327fa3a735f8253fa0c4da353b15ea76fe5
Status: Downloaded newer image for bitnami/minideb:latest

pi@raspberrypi:~ $ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
bitnami/minideb     latest              c6fac3ec5eda        46 hours ago        61.8MB

pi@raspberrypi:~ $ uname -a
Linux raspberrypi 5.4.51-v8+ #1333 SMP PREEMPT Mon Aug 10 16:58:35 BST 2020 aarch64 GNU/Linux

pi@raspberrypi:~ $ docker run --rm -it bitnami/minideb ls /
bin   dev  home  media  opt   root  sbin  sys  usr
boot  etc  lib   mnt    proc  run   srv   tmp  var
```

**Comment by beltran-rubo** [comment]
It seems the issue could be related to the Docker client and the multiple arch variants https://github.com/moby/moby/issues/34875  Could you try updating the docker client version? if not, as you mentioned, you can pull the one with 'arm' in the tag itself.
