### ISSUE TITLE
Arm32 or Arm/v7 support

### ISSUE THREAD

**Issue by rmiddle** [bitnami/minideb#114]
**Description**
I was wondering if arm32 support is on your roadmap? A lot of downstream tools (Postgres, Mongo, Redis) support arm32, but the docker images published are 64bit only. Is it something you can/would like to support? Especially nowadays with Popularity of Raspberry PI and other Arm32 based SBC.  Lots of people are using ARM for embed projects that minideb would benfit.

**Comment by migruiz4** [comment]
Hi @odidev,

Our Bitnami images don't have support for ARM64 yet, although, it is in our roadmap to release the entire catalog for ARM64 in the future.

At the moment, only our base image bitnami/minideb has support for ARM64: bitnami/minideb#90

For more information about the status of the catalog migration, please refer to the following issue: https://github.com/bitnami/charts/issues/7305

**Comment by ddelange** [comment]
For 32bit ARM xref #119
