### ISSUE TITLE
About language

### ISSUE THREAD

**Issue by aluopy** [bitnami/minideb#117]
How to install Chinese language package
Thank you

**Comment by juan131** [comment]
Hi @aluopy 

Minideb is a Debian-based image, therefore you can install any language package following the Debian distro instructions:

- https://wiki.debian.org/ChangeLanguage

**Comment by aluopy** [comment]
> Hi @aluopy
> 
> Minideb is a Debian-based image, therefore you can install any language package following the Debian distro instructions:
> 
> * https://wiki.debian.org/ChangeLanguage

thanks
