### ISSUE TITLE
Updates not published to Docker Hub

### ISSUE THREAD

**Issue by mpoindexter** [bitnami/minideb#132]
**Description**

It appears that new builds are no longer available on Docker Hub, the latest version was published a month ago according to https://hub.docker.com/r/bitnami/minideb/tags

I see that CI in this repo is failing since approximately that time, but not sure if it is related.

Is this intentional and I should not expect minideb to be updated in Docker Hub on a nightly basis, or is this a bug?

**Comment by agomezmoron** [comment]
Hi @mpoindexter ,

Thank you for your report. We have reviewed @sengi's PR and merged it. 

Thanks for reporting!
