### ISSUE TITLE
Cannot install `mysql-server` package

### ISSUE THREAD

**Issue by sameersbn** [bitnami/minideb#16]
The `mysql-server` package installation prompts users to enter a password during build time. The `DEBIAN_FRONTEND=noninteractive` variable does not seem to have any effect  on this prompt. I tested the case using `apt-get` as well as `install_packages` helper script, with both attempts failing to install the `mysql-server` package.

```Dockerfile
FROM bitnami/minideb:latest
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y mysql-server
```

```Dockerfile
FROM bitnami/minideb:latest
RUN install_packages mysql-server
```

**Comment by chipironcin** [comment]
Found some possible explanations in this thread:
http://stackoverflow.com/questions/7739645/install-mysql-on-ubuntu-without-password-prompt

Using `-E`:
```
export DEBIAN_FRONTEND=noninteractive
sudo -E apt-get -q -y install mysql-server
```
or using `debconf-set-selections`.

**Comment by james-w** [comment]
I can't reproduce this with either Dockerfile. I've no idea why that might be.

**Comment by james-w** [comment]
Ah, if I remove the `DEBIAN_FRONTEND=noninteractive` from the first then I see the prompt. Not sure why it was having no effect for you.

**Comment by sameersbn** [comment]
interesting.. here's the complete log http://pastebin.com/P4DDwS3x
