### ISSUE TITLE
whats the current image minideb size ?

### ISSUE THREAD

**Issue by y1111** [bitnami/minideb#160]

**Comment by bersace** [comment]
Odd, dive tells me `debian:bookworm` is 116MB but minideb:bookworm is 120MB. What's the point ? Is dive wrong ?

**Comment by carrodher** [comment]
`minideb:bookworm` is a minimalist Debian-based image built specifically to be used as a base image for containers, but it does not have to be the same size as `debian:bookworm`; they are totally different images.
