### ISSUE TITLE
debian stretch repository

### ISSUE THREAD

**Issue by Raizo62** [bitnami/minideb#168]
Hi

Your docker image "bitnami/minideb:stretch" uses the old source.list : 
```
deb http://deb.debian.org/debian stretch main
deb http://security.debian.org/ stretch/updates main
```

But, we can't install anything with this source.list.

The /etc/apt/source.list of Debian 9 (stretch) must contain:
 ```
deb http://archive.debian.org/debian/ stretch main contrib non-free
deb http://archive.debian.org/debian/ stretch-proposed-updates main
deb http://archive.debian.org/debian-security stretch/updates main
```

**Comment by carrodher** [comment]
Debian 9 Stretch has been unsupported since July 2022. Although the container image is published in DockerHub and can be used, there are no new developments, improvements or bug fixes for this version.

**Comment by Raizo62** [comment]
Yes I know. But sometimes we have programs that only work with older versions of software. It's also one of Docker's advantages to meet these needs.
Can't you regenerate this image after changing this file ?

**Comment by carrodher** [comment]
We understand that specific use cases sometimes require older software versions. However, as part of our deprecation and retention policies, we cannot recover or re-release versions that have already been deprecated. This ensures we focus our resources on maintaining and securing the most recent versions.

While we cannot provide the requested version, we recommend using the already available older container images if they suit your requirements. If modifications are needed, you can always use the existing image as a base for a custom Dockerfile. Alternatively, consider updating your program to be compatible with the newer, actively maintained versions for better support and security.
