### ISSUE TITLE
Is perl needed?

### ISSUE THREAD

**Issue by paulpach** [bitnami/minideb#18]
Is perl absolutely needed for this distro?

It is a massive package that fattens this distro.  It can also be easily installed if someone needs it.   So is it necessary to have it in the base distro?  does the package manager use it?

**Comment by sameersbn** [comment]
> Is perl absolutely needed for this distro?

perl is required by a few system utilities.

> It is a massive package that fattens this distro. It can also be easily installed if someone needs it. So is it necessary to have it in the base distro? does the package manager use it?

The perl package installed in here is heavily stripped out to remove the unnecessary bits. it is not as massive as you would generally expect. 

/cc @james-w

**Comment by james-w** [comment]
Hi,

Thanks for your interest and for trying to help us further shrink minideb.

It's only perl-base that is installed, which is a fairly small package.

We would like to remove it, but some core Debian utilities require it so we are stuck with it.

Thanks,

James
