### ISSUE TITLE
mount : PreDepends: libmount1 (>= 2.25) but it is not going to be installed

### ISSUE THREAD

**Issue by TimVNL** [bitnami/minideb#22]
Hi,

I am using minideb as base for my images but as soon as I use:  
  
apt-get remove  
  
I get the following message:
mount : PreDepends: libmount1 (>= 2.25) but it is not going to be installed

How can I fix this?

**Comment by chipironcin** [comment]
Hi @TimVNL 
Can you reproduce it directly on the image without any customization?

I just run the following and got not warning:
```
docker pull bitnami/minideb
docker run -it --rm bitnami/minideb bash
apt-get remove
install_packages vim
apt-get remove
apt-get remove vim
```

**Comment by TimVNL** [comment]
I am still getting the error this is my docker file....

`
  # install basic packages
RUN install_packages  apt-utils && \
    install_packages  bash \
                      curl \
                      tar && \
    # cleanup
    apt-get remove -y curl tar
`

**Comment by sameersbn** [comment]
@TimVNL You are attempting to remove the `tar` package which is required by `libmount1` package. `libmount1` is a very low level system package which is in turn required my a bunch of other system packages. Attempting to remove the tar package would probably take you down the path of removing pretty much all installed packages.

Let us know if this helps. Thanks for your query.

**Comment by TimVNL** [comment]
@sameersbn Thanks for you information leaving tar alone :)

**Comment by sameersbn** [comment]
> leaving tar alone

good call :)
