### ISSUE TITLE
Stretch support

### ISSUE THREAD

**Issue by HanXHX** [bitnami/minideb#32]
Hi,

Can you support Debian Stretch (9) please?

Cheers!

EM

**Comment by james-w** [comment]
Hi,

Yes, we will certainly be adding it when it is released.

I will look at adding a build now that you can use for testing.

Thanks,

James

**Comment by james-w** [comment]
Hi,

I didn't realise that stretch was going to be released the next day :)

`bitnami/minideb:stretch` is available now (as well as being on quay.io and gcr.io
if you prefer)

Please test it and let us know if there are any problems.

Thanks for your interest.
