### ISSUE TITLE
[Docs request] Compare to tklx/base

### ISSUE THREAD

**Issue by elimisteve** [bitnami/minideb#35]
Does this have advantages over https://github.com/tklx/base (which can be used with CoreOS's [rkt](https://coreos.com/rkt/docs/latest/))?  Thanks.

**Comment by james-w** [comment]
Hi, thanks for the pointer. I will look in more detail, but it sounds like they are very similar indeed.

FWIW minideb isn't strictly for docker either, as it builds a base tarball, then imports it in to docker. I've never tried it with a different runtime though.

**Comment by elimisteve** [comment]
Thanks! :+1:
