### ISSUE TITLE
curl or wget pre installed

### ISSUE THREAD

**Issue by melezhik** [bitnami/minideb#36]
Hi!

I am going to use your image, the only hurdle is that it lacks an http client ( wget or curl ).
My usage logic implies I bootstrap all the dependencies on minideb container via `curl $some-url | bash` 

Any ideas?

**Comment by chipironcin** [comment]
Hello @melezhik 
Including `curl` or `wget` in the image would increase it size, losing one of the main claims of it.

You can use https://github.com/bitnami/minideb-extras which includes curl and some other extra packages that may be useful.

You can also create your own image like:

```
FROM bitnami/minideb
RUN install_packages curl ca-certificates
```

**Comment by melezhik** [comment]
HI @chipironcin  minideb-extras works for me! Thanks

**Comment by james-w** [comment]
Hi,

You can also just include

`RUN install_packages curl ca-certificates`

as the first instruction in your `Dockerfile`, before you run the `curl | bash` instruction.

**Comment by melezhik** [comment]
Yeah, I see. Actually I don't use Dockerfile for building image or provisioning , I use [ducky ](https://github.com/melezhik/ducky)

**Comment by mteodori** [comment]
Since minded-extras has been deprecated, what is the alternative to avoid a Dockerfile and build/publish your own image?
