### ISSUE TITLE
Compare to Debian Slim

### ISSUE THREAD

**Issue by nikolay** [bitnami/minideb#37]
You add `insserv`, `startpar`, `sysv-rc`, which `debian:stable-slim` doesn't carry. Any reason why?

**Comment by nikolay** [comment]
Compared to `tklx/base:0.1.1`, you add `adduser`, `libcap-ng0`, `libfdisk1`, `liblz4`, and `ncurses-base`.

**Comment by james-w** [comment]
In Jessie `sysv-rc` shipped `/usr/sbin/update-rc.d`, but this is now in `init-system-helpers`, so those 3 packages could be removed in later releases.

`apt` depends on `adduser`, so I'm not sure how `tklx` removes that. `libcap-ng0` is a transitive dependency of that.

`libfdisk1` is a dependency of `util-linux`

`liblz4` doesn't seem to be installed in the stretch image.

`ncurses-base` ships the terminfo files, which are required for some console programs to work (e.g. top). They could be removed, or alternatively a few could be included without installing ncurses-base.

**Comment by nikolay** [comment]
@james-w Any chance to trim the images further by removing those?

**Comment by vikas027** [comment]
It would be good if a comparison can be added to the docs.

**Comment by miguelaeh** [comment]
Hi @vikas027 ,
This is a really old issue. Are you experiencing any issues with the image?
