### ISSUE TITLE
Failed to fetch when install_packages

### ISSUE THREAD

**Issue by TimVNL** [bitnami/minideb#38]
Hello,

I am getting the following error when I do:
`install_packages curl`

```
E: Unable to locate package curl
apt failed, retrying
W: Failed to fetch http://httpredir.debian.org/debian/dists/stretch/InRelease  Temporary failure resolving 'httpredir.debian.org'
W: Failed to fetch http://security.debian.org/dists/stretch/updates/InRelease  Temporary failure resolving 'security.debian.org'
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
E: Unable to locate package curl
```

I'm using Docker CE 17.09 on Mac OS 10.13

**Comment by james-w** [comment]
Hi,
```
...
Temporary failure resolving 'httpredir.debian.org'
...
```

This sounds like your network had a problem resolving DNS. Assuming it's not a temporary problem
then I think there might be a configuration problem with your docker install.

I assume that other cases work ok for you though?

**Comment by TimVNL** [comment]
I have a fresh docker install and I only have the issue with the latest release the jessie release is fine

**Comment by jgreth** [comment]
Same Problem here. Fresh install and error only appears in stretch. 

My Dockerfile starts like:
```dockerfile
FROM bitnami/minideb:stretch
# Get CURL
RUN install_packages curl ca-certificates tar
[...]
```

**Comment by james-w** [comment]
That Dockerfile builds fine for me, so I'm not sure what the difference would be that
causes you to see an error.
