### ISSUE TITLE
Busybox, Musl end Extraction

### ISSUE THREAD

**Issue by linuxslide** [bitnami/minideb#41]
Hello guys!
I have two questions about the project:

1 - Do you have plans to replace parts of Coreutils using Busybox. And plans to use musl or dietlib instead of glibc? 

2 - I'd like to extract the base system to make a live usb, I'v check this link http://mr.gy/blog/build-vm-image-with-docker.html and found this instructions:

docker build -t <YOUR-IMAGE> ...
docker create --name=<YOUR-CONTAINER> <YOUR-IMAGE>
dd if=/dev/zero of=disk.img bs=1 count=0 seek=1G
mkfs.ext2 -F disk.img
sudo mount -o loop disk.img /mnt
docker export <YOUR-CONTAINER> | sudo tar x -C /mnt
sudo umount /mnt

But I'm really not ashamed to ask if is there a lazy way do get this source. Do you know?
Tks and congratulations for the great job!!!

**Comment by HatchiFr** [comment]
Why you dont use alpine ? Based on BusyBox and musl.

**Comment by james-w** [comment]
Sorry, I somehow missed the original report.

> 1 - Do you have plans to replace parts of Coreutils using Busybox. And plans to use musl or dietlib instead of glibc?

No, this is a Debian system, if you want Busybox and musl then something like Alpine would be your option as HatchiFr says

> 2 - I'd like to extract the base system to make a live usb, I'v check this link http://mr.gy/blog/build-vm-image-with-docker.html and found this instructions:

The instructions in the link seem like a good start. I don't know exactly which steps need to be done to
make the system boot from a live USB though, you'll have to do some experimentation.
