### ISSUE TITLE
license clarity

### ISSUE THREAD

**Issue by mikedlr** [bitnami/minideb#61]
Your licensing currently states that minideb is licensed under the Apache software license.  Whilst that's probably true of all parts you created that doesn't cover everything since you are using components under other licenses.  

You might want to add a clause [like the one in CentOS](http://mirror.centos.org/centos/7/os/x86_64/EULA):

> The Distribution is released ~~as GPLv2~~ under the Apache License, Version 2.0. Individual packages in the distribution come with their own licences.

or similar.

**Comment by james-w** [comment]
Hi,

Thanks for this. Are you referring to the code that generates the images, or the images themselves?

Thanks,

James
