### ISSUE TITLE
install_packages acts as though you run it once

### ISSUE THREAD

**Issue by nik9000** [bitnami/minideb#74]
I'm using minideb but have to install packages in a few stages. I use `install_packages` to get the retry and `apt-get update` but I wish I could send it a flag not to clean the cache. And if the cache were still there it wouldn't `apt-get update`.

**Comment by james-w** [comment]
Hi,

Thanks for the suggestion.

The way that docker layers work mean that the cache files would then be in the resulting image as they would be saved in that intermediate layer. Unless you are running `install_packages` multiple times in the same `RUN` line?

I'm not sure it's worth adding this behaviour to `install_packages` as its primary purpose is to not do this. I think you can just use `apt update && apt install` as usual to get the behaviour you want. Would there be another reason you particularly want to use `install_packages`?

Thanks,

James

**Comment by nik9000** [comment]
> The way that docker layers work mean that the cache files would then be in the resulting image as they would be saved in that intermediate layer.

Ah! I use multi-stage builds to fetch dependencies and copy the important bits to a "final" image and I'd thought I could share the cache between the stages. And, I guess, you could indeed do that and my proposal would help with that. *But* I think it'd be pretty easy to accidentally include the cache in the final image too.

Thanks for replying!
