### ISSUE TITLE
Arm64 support

### ISSUE THREAD

**Issue by JorritPosthuma** [bitnami/minideb#76]
Hi!

I was wondering if arm64 support is on your roadmap? A lot of downstream tools (Postgres, Mongo, Redis) support arm64, but the docker images published are amd64 only. Is it something you can/would like to support? Especially nowadays with ARM64 based AWS instances (Amazon EC2 A1) and the new Raspberry Pi 4, it becomes more and more useful :).

**Comment by beltran-rubo** [comment]
Thanks for your feedback. At this moment we do not have any ETA for arm64 platform. Right now we are focusing on expanding and improving our containers & Kubernetes Charts catalog.

**Comment by JorritPosthuma** [comment]
Alright! Thanks for letting me know :). Is it possible to use normal Debian as base image? Or is that missing a lot?

**Comment by beltran-rubo** [comment]
Do you mean to replace FROM:minideb and use other Debian? It should work because minideb is just a small version of a Debian distribution but it is only supported a x86_64 architecture. The binaries for postgresql, mongo, redis, ... are also x86_64.

**Comment by JorritPosthuma** [comment]
Yes, that was the idea. Switch to `FROM debian` and if the Postgres binary is build as part of the Dockerfile, then that's it. But otherwise replace it with an arm64 build :).

**Comment by beltran-rubo** [comment]
In that case that would not work. The containers do not run the compilation at build time. The Postgres binaries or other component binaries are already compiled for x86_64 so will not work on top of arm64.

**Comment by rkristelijn** [comment]
> Hi!
> 
> I was wondering if arm64 support is on your roadmap? A lot of downstream tools (Postgres, Mongo, Redis) support arm64, but the docker images published are amd64 only. Is it something you can/would like to support? Especially nowadays with ARM64 based AWS instances (Amazon EC2 A1) and the new Raspberry Pi 4, it becomes more and more useful :).

+1

**Comment by pmundt** [comment]
FYI, I just needed the same thing for provisioning multi-arch [accelerator base containers](https://github.com/adaptant-labs/accelerator-base-containers), so I ended up just hacking up the build scripts, building it on amd64 and arm64 and manually constructing the manifest. There's now an [adaptant/minideb](https://hub.docker.com/repository/docker/adaptant/minideb/tags?page=1) multi-arch image that includes both.

It should be easy enough to hack up the scripts to use buildx, but I haven't had the time to look at this yet.

**Comment by james-w** [comment]
> It should be easy enough to hack up the scripts to use buildx, but I haven't had the time to look at this yet.

One concern would be whether that produced reproducible builds.


Does `debian-slim` have arm64 images?

**Comment by pmundt** [comment]
@james-w Yes, of course, there is no real difference in image size for the x86_64 and arm64 builds.

**Comment by james-w** [comment]
Yes, `debian-slim` has arm64 images, so that would be an option for anyone that wants minimial debian images for arm64 until minideb has support.
