### ISSUE TITLE
Supporting Raspbian hosts: add keyring environment variable

### ISSUE THREAD

**Issue by sbrl** [bitnami/minideb#83]
If I try to build minideb on a Raspberry Pi 4 with Raspbian installed, I get the following error:

```
make[1]: Leaving directory '/home/dietpi/minideb'
./mkimage /home/dietpi/minideb/build/buster.tar buster
cp: cannot stat '/usr/share/keyrings/debian-archive-keyring.gpg': No such file or directory
make: *** [Makefile:28: buster] Error 1
```

To fix it, I had to tweak `mkimage`. Here are the changes I had to make: https://ybin.me/p/1249eb31d3d4fcd9#NFUFW1QRI59T/ojae73HMaq3wtfv9nIaTfmXcpO5LZg=

In order to allow for seamless building on Raspbian hosts, I propose either the following solutions:

1. Add an environment variable for specifying the keyring to copy
2. Auto-detect the host distribution with something like `lsb_release -i` and if Raspbian is detected, then alter the keyring path.

**Comment by beltran-rubo** [comment]
Minideb now supports ARM builds, you can find them at https://hub.docker.com/r/bitnami/minideb

**Comment by sbrl** [comment]
Thanks! Does it work if I build it locally myself though on a raspberry pi?
